CREATE OR REPLACE PACKAGE A_TESTLOG
AS
  PROCEDURE ADD_MESSAGE(MESS IN VARCHAR2);
  PROCEDURE GET_NUM(NUM OUT INTEGER);
END A_TESTLOG;
@

CREATE OR REPLACE PACKAGE BODY A_TESTLOG
AS

  PROCEDURE ADD_MESSAGE(MESS IN VARCHAR2)
  AS
  BEGIN
   INSERT INTO  MESSAGES VALUES('FROM PACKAGE ' || MESS);
  END;
   
  PROCEDURE GET_NUM(NUM OUT INTEGER)
  AS
  BEGIN
    SELECT COUNT(*) INTO NUM FROM MESSAGES;
  END;  

END A_TESTLOG;
@

CREATE OR REPLACE PACKAGE A_TESTNUM AS 

  N1 NUMBER;
  N2 NUMBER(10);
  N3 NUMBER(14,4);
  
  PROCEDURE PREPARE_DATA;
  
  PROCEDURE PA_INSERT_NUMS(NUM1 IN A_TESTNUM.N1%TYPE, NUM2 IN A_TESTNUM.N2%TYPE,NUM3 IN A_TESTNUM.N3%TYPE);
 
  
  PROCEDURE IO_NUM1(NUMI IN N1%TYPE, NUMO OUT N1%TYPE);
  PROCEDURE IO_NUM2(NUMI IN N2%TYPE, NUMO OUT N2%TYPE);
  PROCEDURE IO_NUM3(NUMI IN N3%TYPE, NUMO OUT N3%TYPE);
  

END A_TESTNUM;
@

CREATE OR REPLACE PACKAGE BODY A_TESTNUM AS

  PROCEDURE PREPARE_DATA
  AS
    I INT;
  BEGIN  
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TABLE_NUM';
    FOR I IN 1..100 LOOP
      PA_INSERT_NUMS(I,I,I + .1234);
    END LOOP;  
    COMMIT;
  END;  
  
  PROCEDURE PA_INSERT_NUMS(NUM1 IN A_TESTNUM.N1%TYPE, NUM2 IN A_TESTNUM.N2%TYPE,NUM3 IN A_TESTNUM.N3%TYPE) AS
  BEGIN 
    INSERT INTO TABLE_NUM VALUES(NUM1,NUM2,NUM3);
  END PA_INSERT_NUMS;

  PROCEDURE IO_NUM1(NUMI IN N1%TYPE, NUMO OUT N1%TYPE) AS
  BEGIN
    NUMO := NUMI + 10;
  END IO_NUM1;

  PROCEDURE IO_NUM2(NUMI IN N2%TYPE, NUMO OUT N2%TYPE) AS
  BEGIN
    NUMO := NUMI + 20;
  END IO_NUM2;

  PROCEDURE IO_NUM3(NUMI IN N3%TYPE, NUMO OUT N3%TYPE) AS
  BEGIN
    NUMO := NUMI + 30;
  END IO_NUM3;

END A_TESTNUM;

