CREATE TYPE PARVARARGS AS VARCHAR(32000) ARRAY[VARCHAR(100)];
CREATE TYPE PARVALS AS VARCHAR(32000) ARRAY[30];

CREATE OR REPLACE PROCEDURE SQL_PREPARESTM(
  OUT PREQUERY VARCHAR(100),
  OUT PREVALS PARVALS,
  IN INS VARCHAR(100),
  IN ARGNAMES PARVALS,
  IN ARGVALS PARVALS 
)
FENCED
NO EXTERNAL ACTION
PROGRAM TYPE SUB
EXTERNAL NAME 'PREPARE:PrepareStm.PrepareS' 
PARAMETER STYLE java 
LANGUAGE java
;