DROP TABLE RES;
DROP TABLE LOGMESS;

CREATE TABLE LOGMESS (MESS VARCHAR(200));

DELETE FROM LOGMESS;

CREATE GLOBAL TEMPORARY TABLE RES (OK INT, OPID BIGINT)
ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK PRESERVE ROWS;


CREATE TABLE TESTSUMMARY(ITEM BIGINT NOT NULL, AMOUNT DECIMAL(15, 4));

DELETE FROM TESTSUMMARY;

INSERT INTO TESTSUMMARY (SELECT ID,NULL FROM ITEM);

CALL CLEAR_ALL_STORES();