select empno,FIRSTNME,MIDINIT,LASTNAME,WORKDEPT,PHONENO,HIREDATE,JOB,
EDLEVEL,SEX,BIRTHDATE,SALARY,BONUS,COMM, 
(SELECT COUNT(*) FROM empattach AS A WHERE A.EMPNO = E.EMPNO) AS NOATTACH from employee e