---------------------------------------------
-- table space for temporary tables
---------------------------------------------
CREATE USER TEMPORARY TABLESPACE usr_tbsp;

-----------------------------------
-- DIMENSION TABLES
-- --------------------------------

CREATE TABLE "PERSON" (
                "ID" BIGINT NOT NULL, 
                "LOGINNAME" CHAR(15) NOT NULL
        );

CREATE TABLE "STORE" (
                "ID" BIGINT NOT NULL , 
                "STORENAME" CHAR(15) NOT NULL
        ) ;

CREATE TABLE "ITEM" (
                "ID" BIGINT NOT NULL,
                "ITEMCODE" CHAR(30) NOT NULL,
                "ITEMSERIAL" VARCHAR(30),
                "DESCRIPTION" VARCHAR(500),
                "SAMPLEPRICE" VARCHAR(50)
        );

--- unique constraints

CREATE UNIQUE INDEX "ITEM_IND_ITEMCODE"
        ON "ITEM"
        ("ITEMCODE");

CREATE UNIQUE INDEX "PERSON_IND_LOGINNAME"
        ON "PERSON"
        ("LOGINNAME");

CREATE UNIQUE INDEX "STORE_IND_STORENAME"
        ON "STORE"
        ("STORENAME");

--- primary keys

ALTER TABLE "ITEM" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY
        ("ID");

ALTER TABLE "PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY
        ("ID");

ALTER TABLE "STORE" ADD CONSTRAINT "STORE_PK" PRIMARY KEY
        ("ID");

-- identity (DB2 specific)

ALTER TABLE "ITEM" ALTER COLUMN "ID" SET GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "PERSON" ALTER COLUMN "ID" SET GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "STORE" ALTER COLUMN "ID" SET GENERATED ALWAYS AS IDENTITY; 

-- logmess - table for log messages
--DROP TABLE LOGMESS;

CREATE TABLE LOGMESS (MESS VARCHAR(200));

---------------------------------------------------
-- FACT TABLES
---------------------------------------------------

------------------------------------------------
--DROP TABLE OPERATION;
--DROP TABLE OPERATIONLINE;

-- create tables


CREATE TABLE "OPERATION" (
                "ID" BIGINT NOT NULL, 
                "OPDATE" DATE NOT NULL, 
                "STORE" BIGINT, 
                "PERSON" BIGINT NOT NULL
        );

CREATE TABLE "OPERATIONLINE" (
                "ID" BIGINT NOT NULL , 
                "ITEM" BIGINT NOT NULL, 
                "AMOUNT" DECIMAL(15 , 4),
                "AMOUNTAVAILABLE" DECIMAL (15 , 4), 
                "VALUE" DECIMAL(20 , 2), 
                "REFERENCELINE" BIGINT, 
                "OPERATION" BIGINT NOT NULL,
        "SEQNUMBER" INTEGER NOT NULL
        ) ;


-- unique constraints


CREATE UNIQUE INDEX "OPERATIONLINE_ID_SEQ"
        ON "OPERATIONLINE"
        ("OPERATION","SEQNUMBER");

-- other constraints


ALTER TABLE "OPERATION" ADD CONSTRAINT "OPERATION_PK" PRIMARY KEY
        ("ID");

ALTER TABLE "OPERATIONLINE" ADD CONSTRAINT "OPERATIONLINE_PK" PRIMARY KEY
        ("ID");


ALTER TABLE "OPERATION" ADD CONSTRAINT "OPERATION_PERSON_FK" FOREIGN KEY
        ("PERSON")
        REFERENCES "PERSON"
        ("ID")
        ON DELETE RESTRICT;

ALTER TABLE "OPERATION" ADD CONSTRAINT "OPERATION_STORE_FK" FOREIGN KEY
        ("STORE")
        REFERENCES "STORE"
        ("ID")
        ON DELETE RESTRICT;

--ALTER TABLE "OPERATIONLINE" DROP CONSTRAINT "OPERATIONLINE_REFERENCELINE_FK";


ALTER TABLE "OPERATIONLINE" ADD CONSTRAINT "OPERATIONLINE_REFERENCELINE_FK" FOREIGN KEY
        ("REFERENCELINE")
        REFERENCES "OPERATIONLINE"
        ("ID")
        ON DELETE RESTRICT;

ALTER TABLE "OPERATIONLINE" ADD CONSTRAINT "OPERATIONLINE_ITEM_FK" FOREIGN KEY
        ("ITEM")
        REFERENCES "ITEM"
        ("ID")
        ON DELETE RESTRICT;

ALTER TABLE "OPERATIONLINE" ADD CONSTRAINT "OPERATIONLINE_OPERATION_FK" FOREIGN KEY
        ("OPERATION")
        REFERENCES "OPERATION"
        ("ID")
        ON DELETE RESTRICT;
        
        
        ALTER TABLE "OPERATION" ALTER COLUMN "ID" SET GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "OPERATIONLINE" ALTER  COLUMN "ID" SET GENERATED ALWAYS AS IDENTITY;

-------------------------------------------------------
-- DASHBOARD
-------------------------------------------------------
--DROP TABLE "ITEMDASHBOARD";

CREATE TABLE "ITEMDASHBOARD" (
     "ITEMID" BIGINT NOT NULL,
     "DELIVERYLINE" BIGINT NOT NULL,
     "CURRENTAMOUNT" DECIMAL(15,4) NOT NULL,
     "CURRENTAVAILABLE" DECIMAL (15,4) NOT NULL,
     "CURRENTVALUE" DECIMAL (20,2)
) ;

ALTER TABLE "ITEMDASHBOARD" ADD CONSTRAINT "ITEMDASHBOARD_PK" PRIMARY KEY
        ("ITEMID","DELIVERYLINE");

ALTER TABLE "ITEMDASHBOARD" ADD CONSTRAINT "ITEMDASHBOARD_OPERATIONLINEID_FK" FOREIGN KEY
    ("DELIVERYLINE")
    REFERENCES "OPERATIONLINE"
    ("ID")
    ON DELETE RESTRICT;

ALTER TABLE "ITEMDASHBOARD" ADD CONSTRAINT "ITEMDASHBOARD_OPERATIONITEMID_FK" FOREIGN KEY
        ("ITEMID")
        REFERENCES "ITEM"
        ("ID")
        ON DELETE RESTRICT;

ALTER TABLE "ITEMDASHBOARD" ADD CONSTRAINT "ITEMDASHBORARD_CHECK" CHECK
  ( CURRENTVALUE > 0 
    AND CURRENTAMOUNT > 0 
    AND CURRENTAVAILABLE >=0 
    AND CURRENTAVAILABLE <= CURRENTAMOUNT);

--------------------------------------------------------
-- TEMPORARY TABLES
--------------------------------------------------------

--DROP TABLE "TEMP_ITEM_CODES_LIST";

CREATE GLOBAL TEMPORARY TABLE "TEMP_ITEM_CODES_LIST" (
  "SESSIONID" VARCHAR(128) NOT NULL,
  "SEQNUMBER" INTEGER NOT NULL,
  "ITEMCODE" CHAR(30) NOT NULL,
  "AMOUNT" DECIMAL(15 , 4) NOT NULL,
  "VALUE" DECIMAL (20,2)
 ) ON COMMIT PRESERVE ROWS;

CREATE UNIQUE INDEX "TEMP_ITEM_CODES_INDEX" ON "TEMP_ITEM_CODES_LIST"("SESSIONID","SEQNUMBER");

--DROP TABLE TEMP_ITEM_IDS_LIST;

CREATE GLOBAL TEMPORARY TABLE TEMP_ITEM_IDS_LIST (
  "SESSIONID" VARCHAR(128) NOT NULL,
  "SEQNUMBER" INTEGER NOT NULL,
  "ITEMID" BIGINT,
  "OPERATIONLINE" BIGINT,
  "AMOUNT" DECIMAL(15 , 4),
  "AMOUNTRESERVED" DECIMAL (15, 4),  
  "VALUE" DECIMAL(20 , 2) 
 ) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK PRESERVE ROWS;

CREATE UNIQUE INDEX "TEMP_ITEM_ID_INDEX" ON "TEMP_ITEM_IDS_LIST"("SESSIONID","SEQNUMBER");

