// DO NOT EDIT THIS FILE - it is machine generated
#ifndef SPL_JNIFunctions_application_h
#define SPL_JNIFunctions_application_h

#include <SPL/Runtime/Function/SPLJavaFunction.h>
#include <SPL/Runtime/Type/SPLType.h>

namespace SPL {
namespace JNIFunctions {
namespace application {
class SPL_JNIFunctions {
public:

// Generated from application.PowerBIAuthenticateImpl in lib/F.jar at Sat Jan 02 23:45:57 CET 2016
static SPL::ustring PowerBIAuthenticate(SPL::ustring const & arg1, SPL::ustring const & arg2, SPL::ustring const & arg3) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("PowerBiOper", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "lib/F.jar", "application.PowerBIAuthenticateImpl", "PowerBIAuthenticate", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", "application", "<string T> public T PowerBIAuthenticate(T oauth_username, T oauth_password, T oauth_clientid)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jstring obj2 = env->NewString((jchar *) arg2.getBuffer(), (jsize) arg2.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jstring obj3 = env->NewString((jchar *) arg3.getBuffer(), (jsize) arg3.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jstring resObj = (jstring) env->CallStaticObjectMethod(classGlobalRef, mid, obj1, obj2, obj3);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    env->DeleteLocalRef(obj2);
    env->DeleteLocalRef(obj3);
    if (resObj != NULL) {
        const jchar *chars = env->GetStringChars(resObj, NULL);
        if (chars == NULL)
            SPL::SPLJavaFunction::throwCreateError(func);
        SPL::ustring result((const UChar *) chars, (int32_t) env->GetStringLength(resObj));
        env->ReleaseStringChars(resObj, chars);
        env->DeleteLocalRef(resObj);
        return result;
    } else {
        return SPL::ustring::fromUTF8("");
    }
}

// Generated from application.PowerBIAuthenticateImpl in lib/F.jar at Sat Jan 02 23:45:57 CET 2016
static SPL::rstring PowerBIAuthenticate(SPL::rstring const & arg1, SPL::rstring const & arg2, SPL::rstring const & arg3) {
    SPL::ustring result = PowerBIAuthenticate(SPL::ustring::fromUTF8(arg1), SPL::ustring::fromUTF8(arg2), SPL::ustring::fromUTF8(arg3));
    return SPL::ustring::toUTF8(result);
}

// Generated from application.PowerBIAuthenticateImpl in lib/F.jar at Sat Jan 02 23:45:57 CET 2016
template <SPL::int32 msize>
static SPL::bstring<msize> PowerBIAuthenticate(SPL::bstring<msize> const & arg1, SPL::bstring<msize> const & arg2, SPL::bstring<msize> const & arg3) {
    SPL::rstring result = PowerBIAuthenticate((SPL::rstring) arg1, (SPL::rstring) arg2, (SPL::rstring) arg3);
    return (SPL::bstring<msize>) result;
}

};
}
}
}
#endif
