CREATE OR REPLACE FUNCTION GETDATE()
RETURNS TIMESTAMP
RETURN CURRENT TIMESTAMP
@

CREATE OR REPLACE FUNCTION DBO.DATEADD_DD(IN NOD INT, IN DAT TIMESTAMP)
RETURNS TIMESTAMP
RETURN DAT + NOD DAYS
@

CREATE OR REPLACE FUNCTION DBO.DATEADD_MM(IN NOD INT, IN DAT TIMESTAMP)
RETURNS TIMESTAMP
RETURN DAT + NOD MONTHS
@

CREATE OR REPLACE FUNCTION DBO.DATEADD_MI(IN NOD INT, IN DAT TIMESTAMP)
RETURNS TIMESTAMP
RETURN DAT + NOD MINUTES
@

CREATE OR REPLACE FUNCTION DBO.DATEDIFF_DD(IN STARTDATE TIMESTAMP, IN ENDDATE TIMESTAMP)
RETURNS INT
RETURN TIMESTAMPDIFF(16,CHAR(ENDDATE -STARTDATE))
@

CREATE OR REPLACE FUNCTION DBO.DATEDIFF_MM(IN STARTDATE TIMESTAMP, IN ENDDATE TIMESTAMP)
RETURNS INT
RETURN TIMESTAMPDIFF(64,CHAR(ENDDATE -STARTDATE))
@

CREATE OR REPLACE FUNCTION DBO.DATEDIFF_MI(IN STARTDATE TIMESTAMP, IN ENDDATE TIMESTAMP)
RETURNS INT
RETURN TIMESTAMPDIFF(4,CHAR(ENDDATE -STARTDATE))
@

CREATE OR REPLACE FUNCTION DBO.DATEPART_HH(IN da TIMESTAMP) 
RETURNS INT
  SOURCE HOUR(TIMESTAMP)
@

CREATE OR REPLACE FUNCTION DBO.DATEPART_SS(IN da TIMESTAMP) 
RETURNS INT
  SOURCE SECOND(TIMESTAMP)
@

CREATE OR REPLACE FUNCTION DBO.DATEPART_MI(IN da TIMESTAMP) 
RETURNS INT
  SOURCE MINUTE(TIMESTAMP)
@

CREATE OR REPLACE FUNCTION ISNULL(IN S1 VARCHAR(32672),IN S2 VARCHAR(32672)) 
RETURNS VARCHAR(32672)
  RETURN COALESCE(S1,S2)
@

CREATE OR REPLACE FUNCTION CHARINDEX(VARCHAR(32672),VARCHAR(32672))
RETURNS INTEGER
SOURCE LOCATE(VARCHAR(32672), VARCHAR(32672))
@  

CREATE OR REPLACE FUNCTION SUBSTRING (IN STR VARCHAR(32672),IN STA INT, IN LEN INT)
RETURNS VARCHAR(32672)
  RETURN SUBSTRING(STR,STA,LEN,CODEUNITS16)
@

CREATE OR REPLACE FUNCTION REPLICATE(VARCHAR(4000),INT )
RETURNS VARCHAR(32672)
SOURCE REPEAT(VARCHAR(4000),INT)
@ 

CREATE OR REPLACE FUNCTION STUFF(VARCHAR(32672),INT, INT,VARCHAR(32672))
RETURNS VARCHAR(32672)
SOURCE INSERT(VARCHAR(32672),INT, INT,VARCHAR(32672))
@

CREATE OR REPLACE FUNCTION LEN(VARCHAR(32672))
RETURNS INT
SOURCE LENGTH(VARCHAR(32672))
@