CREATE FUNCTION DATEADD_DD(@days INT, @da DATETIME)
RETURNS DATETIME
AS 
BEGIN
  RETURN DATEADD(dd,@days,@da)
END

CREATE FUNCTION DATEADD_MM(@mins INT, @da DATETIME)
RETURNS DATETIME
AS 
BEGIN
  RETURN DATEADD(mm,@mins,@da)
END    

CREATE FUNCTION DATEADD_MI(@mins INT, @da DATETIME)
RETURNS DATETIME
AS 
BEGIN
  RETURN DATEADD(mi,@mins,@da)
END    

CREATE FUNCTION DATEDIFF_DD(@startdate DATETIME,@enddate DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEDIFF(dd,@startdate,@enddate)
END  

CREATE FUNCTION DATEDIFF_MM(@startdate DATETIME,@enddate DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEDIFF(mm,@startdate,@enddate)
END

CREATE FUNCTION DATEDIFF_MI(@startdate DATETIME,@enddate DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEDIFF(mi,@startdate,@enddate)
END  

CREATE FUNCTION DATEPART_HH(@da DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEPART(hh,@da)
END  

CREATE FUNCTION DATEPART_MI(@da DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEPART(mi,@da)
END
  
CREATE FUNCTION DATEPART_SS(@da DATETIME)
RETURNS INT
BEGIN 
  RETURN DATEPART(ss,@da)
END  
